config/routes.rb
Rails.application.routes.draw do
  
  resources :comments
  resources :tasks
  resources :users
  get "/", to: 'pages#home', as: 'home'
  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create", as: "signup_complete"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create", as: "sessions"
  delete "/logout", to: "sessions#destroy", as: "logout"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :task

    validates :content, length: {maximum: 140} 
end

app/models/task.rb
class Task < ApplicationRecord

    belongs_to :assignee, foreign_key: "assignee_id", class_name: "User"
    belongs_to :assigner, foreign_key: "assigner_id", class_name: "User" 
    has_many :comments
     
    validates :assignee_id, :title, :content, presence: true
    validates :title, uniqueness: true

    after_initialize :task_status
    
    
    def self.show_user_assigned_tasks(user)
        Task.all.select {|task| task.assignee_id == user.id}
    end

    private

    def task_status
        self.status ||= "Not started"
    end

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password 
    validates :username, presence: true
    validates :username, uniqueness: true
    
    has_many :task_assignees, foreign_key: :assigner_id, class_name: "User"
	has_many :assignees, through: :task_assignees
    
    has_many :task_assigners, foreign_key: :assignee_id, class_name: "User"
    has_many :assigners, through: :task_assigners

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :logged_in?
    
    def current_user
        if session[:user_id]
            User.find(session[:user_id])
        end
    end

    #
    def logged_in?
        !!current_user
    end

    def authorized
        redirect_to(login_path) unless logged_in?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def index
    end

    def new
        @comment = Comment.new
    end

    def create
        byebug
        @comment = Comment.new(comment_params)
        if @comment.valid?
            @comment.save
            redirect_to comment_path(@comment)
        else
            render(:new)
        end
    end

    def show
        @comment = Comment.find(params[:id])
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
        @comment = Comment.find(params[:id])
        @comment.update(comment_params)
        if @comment.valid?
            redirect_to comment_path(@comment)
        else
            render :edit
        end        
    end

    def destroy
    end

    private

    def comment_params
        params.require(:comment).permit(:name, :content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    #if user exists and we can authenticate user's password, we redirect to user and start a session
    def create
        @user = User.find_by(username: params[:username])
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to @user
        else
            redirect_to login_path
        end
    end

    def destroy
        session[:user_id] = nil 
        redirect_to home_path 
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :authorized

    def index
        @tasks = Task.all
    end
    
    def new
        @task = Task.new
        @task.assigner_id = current_user.id
        # byebug
    end

    def create

        @task = Task.new(task_params)
        if @task.valid?
            @task.save
            flash[:notice] = "Task successfully created!"
            redirect_to task_path(@task)
        else
            render :new
        end
    end

    def show
        @task = Task.find(params[:id])
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        # byebug
        @task = Task.find(params[:id])
        @task.update(task_params)
        if @task.valid?
            redirect_to task_path(@task)
        else
            render :edit
        end
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to tasks_path
    end

    private
    
    def task_params
        params.require(:task).permit(:assigner_id, :assignee_id, :title, :category, :priority, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized, except: [:new]

    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.valid?
            @user.save
            session[:user_id] = @user.id
            redirect_to @user
        else
            flash[:errors] = "Invalid username and/or password."
            redirect_to signup_path
        end
    end

    def show
        # byebug
        @user = User.find(params[:id])
        @assigned_tasks = Task.show_user_assigned_tasks(@user)
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end

    private

    def user_params
        params.require(:user).permit(:name, :username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<h1>Create a New Comment</h1>

<%= form_for(@comment) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>
    <%= f.label :content %><br>
    <%= f.text_area :content %><br>
    <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Home</a>  
  <a class="navbar-brand" href="/tasks">All Tasks</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item active">
      <a data-method="delete" class="nav-link" href="/logout" rel="nofollow">Logout<span class="sr-only">(current)</span></a>
      </li>
    <% else %>
      <li class="nav-item active">
      <a class="nav-link" href="/login">Login<span class="sr-only">(current)</span></a>
      </li>
    <% end %>
      <li class="nav-item">
        <a class="nav-link active" href="/users">All Users</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="/tasks/new">Create Task</a>
      </li>
      <li class="nav-item dropdown active">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="/users/">My Profile</a>
          <a class="dropdown-item" href="/tasks/new">My Tasks</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="/signup"></a>
        </div>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>
    

app/views/pages/home.html.erb
<img src=https://wallpaperaccess.com/full/647786.gif alt="">

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<% if @task.errors.any? %>
  <div id="error_explanation">
    <h3>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this post from being saved:
    </h3>
 
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@task) do |f|%>
    <%= f.label :status %><br>
    <%= f.select :status, ['In Progress','Blocked','Completed'] %><br>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :category %><br>
    <%= f.select :category, ['Cleaning', 'Shopping/Supplies', 'Reservations', 'Reimbursements', 'Maintenance']%><br>
    <%= f.label :priority %><br>
    <%= f.select :priority, ['Low', 'Medium', 'High', 'Immediate Action Required']%><br>
    <%= f.label :description %><br>
    <%= f.text_area :content %><br>
    <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks for All Users</h1>
<ul>
   <% @tasks.each do |task| %>
       <li><%= link_to task.title, task_path(task) %></li>
    <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Create a New Task</h1> 

<% if @task.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(@task.errors.count, "error") %>
      prohibited this post from being saved:
    </h4>
 
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@task) do |f|%>
    <%= f.hidden_field :assigner_id, value: @task.assigner_id %>
    <%= f.label :assignee %>
    <%= f.collection_select(:assignee_id, User.all, :id, :name) %><br>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :category %>
    <%= f.select :category, ['Cleaning', 'Shopping/Supplies', 'Reservations', 'Reimbursements', 'Maintenance']%><br>
    <%= f.label :priority %>
    <%= f.select :priority, ['Low', 'Medium', 'High', 'Immediate Action Required']%><br>
    <%= f.label :description %><br>
    <%= f.text_area :content %><br>
    <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<ul>
    <li> Assignee: <%= link_to @task.assignee.name, user_path(@task.assignee) %></li>
    <li> Category: <%= @task.category %></li>
    <li> Status: <%= @task.status %></li>
    <li> Priority: <%= @task.priority %></li>
</ul>

    <b><p>Description:</b> <%= @task.content %></p>
<%= form_tag edit_task_path(@task), method: "get" do %>
    <%= submit_tag "Edit #{@task.title}" %>
<% end %>
<%= form_tag task_path(@task), method: "delete" do %>
    <%= submit_tag "Delete #{@task.title}" %>
<% end %>

app/views/users/index.html.erb
<h2>Current Users</h2>
    
<ul>
    <% @users.each do |user| %>
      <li><%= link_to user.name, user_path(user) %></li>  
    <% end %>
</ul>





    
    

app/views/users/new.html.erb
<h1>Sign Up</h1>

<% if flash[:errors] %>
  <h3><%= flash[:errors] %></h3>
<% end %>
<%= form_for @user do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :username %><br>
  <%= f.text_field :username %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h2>Welcome, <%= @user.name %>! Here is the list of your to-do tasks:</h2>

<ul>
    <% @assigned_tasks.each do |task| %>
      <li>Task: <%= link_to task.title, task_path(task) %></li>
    <% end %>
</ul>

<%if  logged_in? %>
      <%= link_to "Logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "Login", login_path %>
<% end %>